### ISSUE TITLE
SyntaxError: invalid syntax?

### ISSUE THREAD

**Issue by bisonliao** [sknetwork-team/scikit-network#196]
* scikit-network version: 0.10.1
* Python version:3.5
* Operating System: win10

### Description

import sknetwork as skn

python report SyntaxError: invalid syntax for the line "increase: bool = True " in louvain.py

**Comment by QLutz** [comment]
Hi bisonliao,

First of all, thank you for your interest in our package.

The required version of Python for scikit-network is 3.6 and above. In 3.5, type hints were not yet implemented hence the syntax error.

Hope this helps.

**Comment by QLutz** [comment]
Upon reviewing possible fixes for that particular issue, it seems there is no simple workaround to make scikit-network compatible with Python 3.5 without actively damaging code readability.

We therefore recommend upgrading to 3.6.

Yours faithfully.
