### ISSUE TITLE
A question about Bilouvain

### ISSUE THREAD

**Issue by echoshi** [sknetwork-team/scikit-network#378]
Hello，

I am a beginner in the analysis of large graphs. It's glad to be able to find such an excellent package. Thanks for your contributions!

Now I am learning Bilouvain algorithm. Is the code about Bilouvain developed based on the paper "**Efficient Detection of Communities in Biological Bipartite Networks**"? Or another paper?

Look forward to your reply!

**Comment by nathandelara** [comment]
Hello, thank you for your interest!

The BiLouvain implemented in Scikit-network is based on the following paper:
[Modularity and community detection in bipartite networks](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.76.066102)

We have used some tricks to simplify the implementation but still, the objective function is the one described there.

At first sight, it is not obvious that this corresponds to the formulas in the paper that you found. It would require further investigation to confirm whether the two definitions of *bimodularity* are identical or not.

Hope this helps.

**Comment by echoshi** [comment]
> Hello, thank you for your interest!
> 
> The BiLouvain implemented in Scikit-network is based on the following paper:
> [Modularity and community detection in bipartite networks](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.76.066102)
> 
> We have used some tricks to simplify the implementation but still, the objective function is the one described there.
> 
> At first sight, it is not obvious that this corresponds to the formulas in the paper that you found. It would require further investigation to confirm whether the two definitions of _bimodularity_ are identical or not.
> 
> Hope this helps.

Ok. Thanks for your reply！
