### ISSUE TITLE
Stochastic Block Model Documentation and new clustering algorithm implementation

### ISSUE THREAD

**Issue by clbonet** [sknetwork-team/scikit-network#400]
Hi,

I noticed that the link of the article for the stochastic block model is the wrong one : [https://arxiv.org/abs/0803.0476 ](https://arxiv.org/abs/0803.0476) instead of [https://arxiv.org/pdf/0705.4485.pdf](https://arxiv.org/pdf/0705.4485.pdf)

I needed to generate a stochastic block model with p_in<p_out but it is still not directly possible. It would be great if you could make it.

I am actually working on EM type algorithms for graphs, and I wondered if you would be interested in adding algorithms such as the variational EM : [VEM](http://pbil.univ-lyon1.fr/members/fpicard/franckpicard_fichiers/pdf/DPR08.pdf)
I implemented it using numba to speed up the loops. But it would probably be better to use cython. Unfortunately, I don't really know it.

**Comment by nathandelara** [comment]
Hi,

Thank you for your comments.
We have modified the reference and we are currently working in making the "p_in < p_out" option available. This should be ready for the next release !
Still, keep in mind that such graphs are likely to be dense which is not exactly in the spirit of this package...

For the paper, one option could be for you to open a PR with a pure Python implementation and then we could guide you with the Cython.
As you are already familiar with numba, a good start is to have a code that is @njit compatible.

**Comment by tbonald** [comment]
Hi,
You can now set any parameters p_in and p_out in the version of the SBM available on the branch develop.
Thanks for the suggestion!

**Comment by clbonet** [comment]
Hi,
Thank you for your replies.

I will probably open a PR in the next days.
