### ISSUE TITLE
Possible Misleading Soft Clustering Map graph results

### ISSUE THREAD

**Issue by skyler14** [sknetwork-team/scikit-network#446]
I took the star_wars demo dataset and ran it through the bi-louvain soft clustering example. I decided to print out what values we're getting for the clusters as well to see how they matched up. 

![image](https://user-images.githubusercontent.com/849064/94211956-7636ac00-fe98-11ea-84e2-32327845acb5.png)

While things seem fine in the image when you compare the values of the scores: 
[('Jabba', 0.5), ('Greedo', 1.0), ('Vador', 0.3333333333333333), ('Boba', 0.0)] 
[('A New Hope', 0.6666666666666666), ('The Empire Strikes Back', 0.0), ('Return Of The Jedi', 0.3333333333333333)]

You can see that Vader and RoTJ had the same score but different colors. I've looked for an explanation of what your soft clustering scores are based on to figure out what that could mean but it seems like it just used the max and min values for rows and columns respectively to color the rows/columns on a spectrum for each. 

* scikit-network version: 0.19.0
* Python version: 3.8.5
* Operating System: Windows 10

### Description

I decided to try the bi-louvain demo using the Star Wars dataset.

### What I Did

```
graph = star_wars(metadata=True)
names_row = graph.names_row
names_col = graph.names_col
biadjacency = graph.biadjacency
bilouvain = BiLouvain()
bilouvain.fit(biadjacency)
labels_row = bilouvain.labels_row_
labels_col = bilouvain.labels_col_
image = svg_bigraph(biadjacency, names_row, names_col, labels_row, labels_col)
scores_row = bilouvain.membership_row_[:,1].toarray().ravel()
scores_col = bilouvain.membership_col_[:,1].toarray().ravel()
image = svg_bigraph(biadjacency, names_row, names_col, scores_row=scores_row, scores_col=scores_col)
with open("tmp.svg", "w") as text_file:
    print(image, file=text_file)
print(list(zip(names_row,scores_row)),list(zip(names_col,scores_col)))
```

P.S.: Not sure if Vader --> Vador was deliberate change to french spelling or a typo.

**Comment by tbonald** [comment]
Thanks for your feedback!
Fixed on the develop branch (including the typo on Vader :-)
Here is the result on your example.
![starwars](https://user-images.githubusercontent.com/26295919/94772944-1326a700-03bb-11eb-973a-03e8de372bc9.jpg)
