### ISSUE TITLE
Ability to read in memory TSV/edgelists

### ISSUE THREAD

**Issue by skyler14** [sknetwork-team/scikit-network#448]
I didn't see a way to flag it as a feature request, but currently unless something is pre-generated in NetSet it's impossible to actually load data in without reading from a file. This can add problems with trying to implement an scikit style pipeline since you have to write data to a file and perform operations after opening the file, and you create needless file i/o overhead everytime you might want to make small changes to the loaded network. Can the edgelist reading functionality be extended to include some kind of internal edgelist/TSV/SciPy Sparse matrix or a clear interface to generate a Bundle be laid out to allow loading of in memory data structures/at least file objects.

* scikit-network version: 0.19.0
* Python version: 3.8
* Operating System:

### Description

I'd like to be able to load in memory entities into scikit network edgelists

### What I Did
```
# currently have to do some variation of something like this operation with an edge list dataframe named df
location="tmp"
df.to_csv(location,sep="\t",index=False,header=False)
skn=load_edge_list(loc,bipartite=True,weighted=True)
```

**Comment by QLutz** [comment]
Hello,

Thank you for your question. A function that looks a lot like what you want exists in the `utils` module [here](https://scikit-network.readthedocs.io/en/latest/reference/utils.html#sknetwork.utils.edgelist2adjacency) (or rather in your case the one just below). Is that of any help to you?

I will update the documentation of the `data` module to point to these functions anyway.

**Comment by skyler14** [comment]
That edgelist2biadjacency function, while helpful, only lets you generate the biadjacency matrix instead of an entire sknetworks.util.Bunch, which means that you have to strip your edgelist of its labels and feed it in an integer form, and then seperately manage all the relevant label tracking and other functionality that normally a Bunch loaded by something like load_edge_list automatically handles.

**Comment by QLutz** [comment]
The function you describe has been [added](https://github.com/sknetwork-team/scikit-network/commit/7f377ad757df348cc5b5cea7a1a4d22081facf33) as `sknetwork.data.load_edge_list`. The previous function under that name (as well as other parsers) has been renamed to `parse_edge_list`.

This will be included in the next release.
