### ISSUE TITLE
connected_components fails with "AttributeError: 'memoryview' object has no attribute 'max'"

### ISSUE THREAD

**Issue by JanSvejda** [sknetwork-team/scikit-network#449]
* scikit-network version: 0.19.3
* Python version: 3.8.3
* Operating System: Windows 10

### Description
Performing SCC analysis fails due to calling max() on ndarray.data. 

### What I Did
Here is a minimal example for reproducing:
```
>>> import numpy as np
>>> from sknetwork.topology import connected_components
>>> connected_components(np.zeros([4,4]), connection="strong")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jan svejda\Projects\JMCS-TSI\setup-scripts\sct\applications\venv\lib\site-packages\sknetwork\topology\structure.py", line 36, in connected_components
    return sparse.csgraph.connected_components(adjacency, not is_symmetric(adjacency), connection, True)[1]
  File "C:\Users\jan svejda\Projects\JMCS-TSI\setup-scripts\sct\applications\venv\lib\site-packages\sknetwork\utils\check.py", line 74, in is_symmetric
    return np.all(np.abs(sym_error.data) <= tol * np.abs(adjacency.data.max()))
AttributeError: 'memoryview' object has no attribute 'max'
```

**Comment by tbonald** [comment]
Thanks!
This raises 2 issues on the input of the function connected_components in the current version (0.19.3):

1. No numpy array accepted, only sparse csr matrix.
2. No zero matrix accepted (empty graph).

Both issues will be fixed in the next version (see also the develop branch).

What works currently (for instance):
>>> import numpy as np
>>> from sknetwork.topology import connected_components
>>> from scipy import sparse
>>> connected_components(sparse.csr_matrix(np.ones([4,4])), connection="strong")
