### ISSUE TITLE
Cannot Color Nodes

### ISSUE THREAD

**Issue by AlexMRuch** [sknetwork-team/scikit-network#454]
* scikit-network version: 0.18.0
* Python version: 3.7.6
* Operating System: Mac 10.15.3

### Description

For the life of me I cannot get my four node classes to be colored by class for SVG visualization:
```
Labels_named = [] 
for l in Labels: 
    if l == 0: 
        Labels_named.append('blue')
     elif l == 1: 
        Labels_named.append("orange") 
    elif l == 2: 
        Labels_named.append("brown")
     elif l == 3:
         Labels_named.append("fuchsia") 
    else: 
        print("Error: Nothing should be > 3")
 Labels_named[:5]
 image = svg_graph(adjacency, embedding, node_color=Labels_named)
 SVG(image) 
```
![image](https://user-images.githubusercontent.com/22121273/97329071-09268580-184d-11eb-86e2-0f30ea2840c7.png)

Note in the above that I have 4 node classes labeled 0, 1, 2, and 3.

I'm not understanding what I am doing incorrectly. The documentation is not very helpful either. Any guidance would be very helpful!

**Comment by AlexMRuch** [comment]
I also get the same result if I put in svg color codes:
```
Labels_named = []
for l in Labels:
    if l == 0:
        Labels_named.append('#0000FF') # blue
    elif l == 1:
        Labels_named.append("#FFA500") # orange
    elif l == 2:
        Labels_named.append("#A52A2A") # brown
    elif l == 3:
        Labels_named.append("7CFC00") # green
    else:
        print("Error: Nothing should be > 3")
```

**Comment by nathandelara** [comment]
Hi Alex, thanks for reaching out!

Would you mind trying to use the parameter "labels" instead of "node_color"?
The parameter "node_color" is for a default unique color of all nodes.
"labels" should automatically color your nodes by class.

If this works for you, we will try to make the documentation more detailed.

**Comment by AlexMRuch** [comment]
Ah, that solved it! Wonderful! Thanks so much! Really appreciate the timely feedback!
