### ISSUE TITLE
SVG Bipartite Graph output is squished together

### ISSUE THREAD

**Issue by scottagt** [sknetwork-team/scikit-network#472]
* scikit-network version: 0.22.0
* Python version: 3.8
* Operating System: macOS 11.2.1

### Description
I generated a bipartite graph using the svg_bigraph function and the output is really difficult to see as all the nodes are squished together. I tried changing several parameters including width, height, scale, and margin but nothing spaced the nodes out better.

### What I Did

![PastedGraphic-1](https://user-images.githubusercontent.com/25912784/108768325-875a1680-7525-11eb-8cae-3d14911e06c1.png)

**Comment by tbonald** [comment]
Thanks for the feedback.
Have you tried to use the parameters position_row / position_col that specify the position of row / column nodes?
Best.

**Comment by scottagt** [comment]
Hi Thomas,

I did see those but I wasn’t sure what the input should look like to it or how to go about generating such input. If you have any recommendations for that I’d be glad to try give it a shot.

Best,
-Scott
________________________________

**Comment by tbonald** [comment]
Hi Scott,
Actually, the parameter height should work. Have you tried high values (e.g., 1000 or 10,000)?
Otherwise, please share your graph and I can try.
Cheers.

**Comment by scottagt** [comment]
Hi Thomas, thanks for the guidance, I will give it a shot and see what happens. Best, -Scott

On Mar 1, 2021, at 2:24 AM, Thomas Bonald <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Scott,
Actually, the parameter height should work. Have you tried high values (e.g., 1000 or 10,000)?
Otherwise, please share your graph and I can try.
Cheers.

**Comment by tbonald** [comment]
I presume that this issue is solved. Please open a new one if needed. Thanks!
