### ISSUE TITLE
Old version for Python 3.9

### ISSUE THREAD

**Issue by d9d6ka** [sknetwork-team/scikit-network#478]
* scikit-network version:
* Python version: 3.9.4
* Operating System: Win10 20H2

### Description

I'm trying to install scikit-network via `pip`.
Version 0.12.1 is installed.
If I use Python 3.8 then the latest version is installed as expected.

### What I Did

```
pip install scikit-network
```

**Comment by QLutz** [comment]
Thanks for your interest.

Release 0.23.0 offers wheels for Python 3.9.

Please do tell us if you're able to `pip` install and run code with these wheels.

**Comment by d9d6ka** [comment]
Thank you! Works perfectly!
