### ISSUE TITLE
is the PARIS algorithm deterministic? 

### ISSUE THREAD

**Issue by ljmartin** [sknetwork-team/scikit-network#483]
Hi all, thanks for this repo which has proven really useful. 

The PARIS clustering algorithm publication discusses probabilistic similarity between nodes, but is the clustering itself also probabilistic. is it guaranteed to produce the same clustering for a given network? 
Thanks!

**Comment by tbonald** [comment]
Thanks for your feedback!
The Paris algorithm is deterministic, it will always provide the same clustering for a given network.

**Comment by ljmartin** [comment]
Cheers :)
