### ISSUE TITLE
`ImportError: Symbol not found: ____chkstk_darwin` on fresh install for version 0.24.0

### ISSUE THREAD

**Issue by simondelarue** [sknetwork-team/scikit-network#491]
* scikit-network version: 0.24.0
* Python version: 3.7
* Operating System: MacOS 10.13.6

### Description

After fresh install of version 0.24.0, I get `ImportError: Symbol not found: ____chkstk_darwin` error when importing scikit-network package.

### What I Did
I installed scikit-network's latest version using `pip`:
```bash
pip install scikit-network
```

On import I get the following error:  
```python
  File "myFile.py", line 2, in <module>
    import sknetwork
  File "~/opt/anaconda3/envs/graphEmbedEnv/lib/python3.7/site-packages/sknetwork/__init__.py", line 9, in <module>
    import sknetwork.topology
  File "~/opt/anaconda3/envs/graphEmbedEnv/lib/python3.7/site-packages/sknetwork/topology/__init__.py", line 2, in <module>
    from sknetwork.topology.kcliques import Cliques
ImportError: dlopen(~/opt/anaconda3/envs/graphEmbedEnv/lib/python3.7/site-packages/sknetwork/topology/kcliques.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: ~/opt/anaconda3/envs/graphEmbedEnv/lib/python3.7/site-packages/sknetwork/topology/../.dylibs/libomp.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in ~/opt/anaconda3/envs/graphEmbedEnv/lib/python3.7/site-packages/sknetwork/topology/../.dylibs/libomp.dylib
```  
Following previous issues resolution, I tried to install the package following contributor guideline (`python setup.py develop`), which was a success.

Thanks very much !

**Comment by QLutz** [comment]
Hello,

Thanks for your feedback.

This issue seems to be related to our recent transition to GitHub Actions and has been documented on other packages ([here](https://github.com/scikit-learn/scikit-learn/issues/19063) and [here](https://github.com/nodegui/nodegui/issues/391) for example).

We'll check what they've done and chose how to fix this.

**Comment by simondelarue** [comment]
Thanks for your help ! :)

**Comment by tbonald** [comment]
Fixed by `python setup.py develop`
Thanks!
