### ISSUE TITLE
find node name

### ISSUE THREAD

**Issue by afrooze** [sknetwork-team/scikit-network#497]
Dear scikit-net
I used page rank algorithm for ranking my directed graph. Now how can find the name of nodes from scores. scores is the output if pageranking algorithm.
thanks

**Comment by afrooze** [comment]
you cannot find

**Comment by tbonald** [comment]
The algorithms of scikit-network (including PageRank) take the graph as input (through its adjacency matrix or biadjacency matrix). Additional information like node names might be available as lists or arrays. 

See https://scikit-network.readthedocs.io/en/latest/tutorials/ranking/pagerank.html for instance

```
import numpy as np

from sknetwork.data import painters
from sknetwork.ranking import PageRank

graph = painters(metadata=True)
# adajcency matrix
adjacency = graph.adjacency
# names
names = graph.names
# PageRank
pagerank = PageRank()
scores = pagerank.fit_transform(adjacency)
# name of top node
names[np.argmax(scores)]
```
