### ISSUE TITLE
No Edge Error

### ISSUE THREAD

**Issue by fatcatZF** [sknetwork-team/scikit-network#500]
* scikit-network version:
* Python version:
* Operating System:

### Description

When there are no edges, i.e., every node is a component; there would be an error.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by QLutz** [comment]
What function are you running?

Please fill in the different parts of the issue template so we can help you.

**Comment by fatcatZF** [comment]
Hi,
when I run `labels = get_connected_components(adjacency)`, if there are no edges, i.e., adjacency.sum()==0; there will be and error.

**Comment by QLutz** [comment]
Indeed, this is the expected behaviour of the function. If need be, surround your code with a `try`/`except` structure.
