### ISSUE TITLE
Not working with numpy 1.22.2?

### ISSUE THREAD

**Issue by jhammarstedt** [sknetwork-team/scikit-network#502]
* scikit-network version: 0.24
* Python version: 3.9

### Description

Is it not compatible with numpy 1.22.2? I just installed the package but get the error: 

### What I Did

```
import sknetwork as skn

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by QLutz** [comment]
What OS are you using?
