### ISSUE TITLE
Error in TSD computation

### ISSUE THREAD

**Issue by danielzuegner** [sknetwork-team/scikit-network#504]
* scikit-network version: `0.24`
* Python version: `3.8.1`
* Operating System: `Ubuntu 20.04`

### Description

I think the way `sknetwork` computes the tree-sampling divergence (TSD) is not correct. There seems to be an issue in the way that the node sampling distribution (`q(z)` in the paper) is computed. Specifically, this [this line](https://github.com/sknetwork-team/scikit-network/blob/master/sknetwork/hierarchy/metrics.py#L213) increases the `q(z)` score by `p(i) * p(j)` effectively (ignoring directionality). However, we also need to take into account `p(i)*p(i)` and `p(j)*p(j)`. Otherwise, the node sampling distribution does not add up to one. 

This is also consistent with the equation in [the TSD paper](https://www.ijcai.org/proceedings/2019/0286.pdf) (p. 2069 top left):
![image](https://user-images.githubusercontent.com/22178797/154249154-f6f42cf4-5ab7-4bb1-9ddc-49cec666a23e.png)
Here, the summation does not specify that `u≠v`, i.e. we should also take into account the "diagonal" entries where `u=v`.

In the code, I think we could achieve this by first "initializing" the node sampling distribution by adding `p(u)*p(u)` to each leaf node `u`'s direct parent in the tree.

**Comment by tbonald** [comment]
Thanks for the notice.
This has been fixed (see develop branch).
The correct code will be available in the next release (coming soon).
