### ISSUE TITLE
Question about Louvain for Bipartite Networks

### ISSUE THREAD

**Issue by OmarFRobledo** [sknetwork-team/scikit-network#509]
Hello,

I've been checking your implementation for what was called before "BiLouvain". I know you merged it with the Louvain code for directed and non-directed general static networks. However, I find it a bit confusing, as I don't see Barber's modularity (or any specific modularity for bipartite networks) cited neither in the documentation or code. Are you still using Barber's modularity from "Modularity and community detection in bipartite graphs"? Is the implementation based on "A novel community detection method in bipartite networks"?

Thanks!
Omar

**Comment by tbonald** [comment]
Hi!

Thanks for the question. 

This is still Barber's modularity. The null model of modularity is based on the adjacency matrix of the associated directed graph, given by:

0 B
0 0

where B is the biadjacency matrix of the bipartite graph. Under Dugue modularity (the default choice), you obtain the null model of Barber's modularity.

You're right, this requires some details in the documentation.
Will do soon.
