### ISSUE TITLE
`svg_bigraph` function does not produce correct svg image when input node name includes  '<' or '>'

### ISSUE THREAD

**Issue by skaimid** [sknetwork-team/scikit-network#511]
* scikit-network version: 0.24.0
* Python version: 3.8.8
* Operating System: Windows 11

### Description

I try to use the `svg_bigraph`  function to draw the images for my study, but the one of the output results is not displayed correctly.

### What I Did

I draw image with:
```
image = svg_bigraph(sparse.csr_matrix(sub_adjacency), 
                    [company[j] for j in cluster_comp_index[i]],
                    [repo[j] for j in cluster_proj_index[i]], 
                    filename="""./louvain_test_sub-{}""".format(i))
```

![image](https://user-images.githubusercontent.com/19438441/158042050-9a3ff991-49a9-4dee-8b6e-82e8c7f3c12b.png)

One of the images doesn't display correctly, it seems to be related to the text "b<>com", then I manually replace the '<' and '>' with '\&lt;' and '\&gt;' and the image can be displayed correctly.

**Comment by tbonald** [comment]
Thanks for the issue raised.
This has been fixed and will be available in the next release.
