### ISSUE TITLE
AttributeError: 'memoryview' object has no attribute 'dtype' when run louvain 

### ISSUE THREAD

**Issue by xf-xue** [sknetwork-team/scikit-network#516]
* scikit-network version:0.25.0
* Python version:3.8
* Operating System:Ubuntu 20.04

### Description
when i run 
`
from sknetwork.clustering import Louvain, modularity
labels = louvain.fit_transform(adjacency)  #adjacency is a adjacent matrix and it‘s type is numpy.ndarray
`

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
`
File "~/lib/python3.8/site-packages/sknetwork/clustering/base.py", line 51, in fit_transform
    self.fit(*args, **kwargs)
  File "~/lib/python3.8/site-packages/sknetwork/clustering/louvain.py", line 252, in fit
    self._secondary_outputs(input_matrix)
  File "~/lib/python3.8/site-packages/sknetwork/clustering/base.py", line 77, in _secondary_outputs
    if np.issubdtype(input_matrix.data.dtype, np.bool_):
AttributeError: 'memoryview' object has no attribute 'dtype'
`
### What I Did
 I do not how to debug it, and it is right when the scikit-network version <= 0.20.0
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by tbonald** [comment]
Thanks for your feedback.
This has been fixed on the Develop branch, and will be available in the next release.
Meanwhile, you can use Louvain on sparse matrices:

`from scipy import sparse`
`from sknetwork.clustering import Louvain`

`labels = louvain.fit_transform(sparse.csr_matrix(adjacency))`
