### ISSUE TITLE
data.load_edge_list is missing in 0.26.0 version

### ISSUE THREAD

**Issue by JiaruiWang** [sknetwork-team/scikit-network#525]
* scikit-network version:0.26.0
* Python version: 3.7
* Operating System: ubuntu 20.04

### Description

skn.data.load_edge_list is missing from the package.
Documentation and tutorial for it are also unavailable.
https://scikit-network.readthedocs.io/en/latest/tutorials/data/index.html#datatag

### What I Did

```
installed 0.26.0
```
Had to roll back to 0.25.0

**Comment by tbonald** [comment]
Please use skn.data.from_edge_list (for edge list) or skn.data.from_adjacency_list (for adjacency list) instead.
Thanks.
