### ISSUE TITLE
Single commodity flow feature

### ISSUE THREAD

**Issue by hcars** [sknetwork-team/scikit-network#526]
### Description

This is a feature request. I would be interested in adding this to the library if the other contributors like it. The [single commodity flow problem](https://en.wikipedia.org/wiki/Maximum_flow_problem) centers on finding the maximum flow from a set of source node to a set of target nodes with edge capacity constraints. We could implement a maximum flow method by wrapping (https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.maximum_flow.html).

**Comment by tbonald** [comment]
I'm moving this thread to the Discussions page as this is not an issue.
Thanks.
