### ISSUE TITLE
from sknetwork.utils import edgelist2adjacency, edgelist2biadjacency

### ISSUE THREAD

**Issue by Sandy4321** [sknetwork-team/scikit-network#559]
* scikit-network version: latest 
* sknetwork.__version__
'0.31.0'
* Python version: 3.10
* Operating System: windows 11

### Description
for
from sknetwork.utils import edgelist2adjacency, edgelist2biadjacency
get
builtins.ImportError: cannot import name 'edgelist2adjacency' from 'sknetwork.utils'

**Comment by tbonald** [comment]
Hello,

This function no longer exists.
Please use the following function:

`from sknetwork.data import from_edge_list`

Thanks.
