### ISSUE TITLE
From Louvain to Leiden: guaranteeing well-connected communities.

### ISSUE THREAD

**Issue by thomashudsonuk** [sknetwork-team/scikit-network#562]
* scikit-network version: 0.31.0
* Python version: N/A
* Operating System: N/A

### Description

As I understand it, the current library doesn't include the Leiden algorithm for community detection but does include the [Louvain algorithm](https://scikit-network.readthedocs.io/en/latest/tutorials/clustering/louvain.html).

As highlighted in [Louvain to Leiden: guaranteeing well-connected communities](https://arxiv.org/abs/1810.08473), authored by [Vincent Traag](https://arxiv.org/search/cs?searchtype=author&query=Traag,+V), [Ludo Waltman](https://arxiv.org/search/cs?searchtype=author&query=Waltman,+L), and [Nees Jan van Eck](https://arxiv.org/search/cs?searchtype=author&query=van+Eck,+N+J), the Louvain algorithm has a **major defect**.

Therefore, are there plans to include the Leiden algorithm in the library, so that users can more easily avoid this defect in the Louvain algorithm? 

Please let me know if I've misunderstood anything or if this request is just not reasonable (for example, too much work - although, I think flagging to users the drawbacks of Louvain for transparency is critical).

### What I Did

Nothing - just raising a question.

**Comment by tbonald** [comment]
Thanks for the suggestion. 
I've moved this to the discussions.

**Comment by thomashudsonuk** [comment]
Thanks
