### ISSUE TITLE
[Feature Request] Add dynamic tree cutting for dendrograms hierarchy cuts

### ISSUE THREAD

**Issue by jolespin** [sknetwork-team/scikit-network#571]
In a future version, would it be possible to add dynamic tree cutting algorithms to scikit-network? I only know of one algorithm which works pretty called the dynamic tree cutting algorithm based in R but there is a Python version as well.  If there are any else you know of, please share as this one is a bit old but widely used. 

Here's the cut algorithms which seem to be wrappers around SciPy:
https://scikit-network.readthedocs.io/en/latest/reference/hierarchy.html#cuts

The original implementation is described here: 
https://academic.oup.com/bioinformatics/article/24/5/719/200751

The Python implementation is here: 
https://github.com/kylessmith/dynamicTreeCut

**Comment by tbonald** [comment]
Great idea, thanks!
I've moved this as a discussion:
https://github.com/sknetwork-team/scikit-network/discussions/572
